services:
  postgres:
    image: postgres:16
    container_name: ecommerce
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-ecommerce}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - ecommerce:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: securepassword
    ports:
      - '8080:80'
    networks:
      - pgnetwork

volumes:
  ecommerce:

networks:
  pgnetwork:
    driver: bridge